seed: "Tile"

scopes:
  - name: "global scope"
    priority: 1
    path: "**.packet"

    rules:
      - name: "mask advertising address"
        path: "**.advertising_address"
        priority: 1
        action:
          ref: "mask_ble_address"
          args:
            rotation_type: "stream"


      - name: "mask_key"
        path: "**.adv_struct[adv_type=0x16].data"
        priority: 2

        condition:
          ref: "is_tile_find"

        action:
          ref: "mask_hex_data"
          args:
            start: 4
            rotation_type: "stream"


